### ISSUE TITLE
Build question dispay component

### ISSUE THREAD

**Issue by gczene** [basemj/habitude-fe#3]
- [x] added to storybook
- [x] must have a code snippet area with highlighting
- [x] may have a description area
- [x] displays answers from an array
- [x] when user select one must send up the selected question object
- [x] jest/enzyme test

**Comment by dshenderson** [comment]
I see the only unticked box is for testing. What happened to TDD? ;)

If part of the motivation for this project is to gain experience, might as well force yourself to be disciplined about writing tests first!

**Comment by basemj** [comment]
I agree, but I had no idea where to start. it might even be all wrong

**Comment by basemj** [comment]
so good to see that SP icon up there
